<?xml version="1.0" encoding="utf-8"?><Database Name="LanguageWeb" Class="LanguageDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Class" Member="Classes">
    <Type Name="Class">
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="programID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="teacherID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="statusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="className" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="room" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="maxStudents" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Class_ClassSchedule" Member="ClassSchedules" ThisKey="ClassID" OtherKey="classID" Type="ClassSchedule" />
      <Association Name="Class_Registration" Member="Registrations" ThisKey="ClassID" OtherKey="classID" Type="Registration" />
      <Association Name="ClassStatus_Class" Member="ClassStatus" ThisKey="statusID" OtherKey="StatusID" Type="ClassStatus" IsForeignKey="true" />
      <Association Name="Teacher_Class" Member="Teacher" ThisKey="teacherID" OtherKey="TeacherID" Type="Teacher" IsForeignKey="true" />
      <Association Name="Program_Class" Member="Program" ThisKey="programID" OtherKey="ProgramID" Type="Program" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ClassSchedule" Member="ClassSchedules">
    <Type Name="ClassSchedule">
      <Column Name="ScheduleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="classID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dayOfWeek" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="startTime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="endTime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Association Name="Class_ClassSchedule" Member="Class" ThisKey="classID" OtherKey="ClassID" Type="Class" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ClassStatus" Member="ClassStatus">
    <Type Name="ClassStatus">
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="statusName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="ClassStatus_Class" Member="Classes" ThisKey="StatusID" OtherKey="statusID" Type="Class" />
    </Type>
  </Table>
  <Table Name="dbo.Consultation" Member="Consultations">
    <Type Name="Consultation">
      <Column Name="ConsultationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fullName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="question" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="requestStatus" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Payment" Member="Payments">
    <Type Name="Payment">
      <Column Name="PaymentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="registrationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="amount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="paymentDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="paymentMethod" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="paymentStatus" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Registration_Payment" Member="Registration" ThisKey="registrationID" OtherKey="RegistrationID" Type="Registration" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PlacementTest" Member="PlacementTests">
    <Type Name="PlacementTest">
      <Column Name="TestID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="studentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="testDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="testTime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="levelRequested" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="suggestedLevel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="resultScore" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Student_PlacementTest" Member="Student" ThisKey="studentID" OtherKey="StudentID" Type="Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Registration" Member="Registrations">
    <Type Name="Registration">
      <Column Name="RegistrationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="studentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="classID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="registrationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Registration_Payment" Member="Payments" ThisKey="RegistrationID" OtherKey="registrationID" Type="Payment" />
      <Association Name="Class_Registration" Member="Class" ThisKey="classID" OtherKey="ClassID" Type="Class" IsForeignKey="true" />
      <Association Name="Student_Registration" Member="Student" ThisKey="studentID" OtherKey="StudentID" Type="Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fullName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="avatar" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="dateOfBirth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Student_PlacementTest" Member="PlacementTests" ThisKey="StudentID" OtherKey="studentID" Type="PlacementTest" />
      <Association Name="Student_Registration" Member="Registrations" ThisKey="StudentID" OtherKey="studentID" Type="Registration" />
      <Association Name="UserAccount_Student" Member="UserAccount" ThisKey="userID" OtherKey="UserID" Type="UserAccount" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Teacher" Member="Teachers">
    <Type Name="Teacher">
      <Column Name="TeacherID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fullName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="avatar" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="expertise" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="bio" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Teacher_Class" Member="Classes" ThisKey="TeacherID" OtherKey="teacherID" Type="Class" />
      <Association Name="UserAccount_Teacher" Member="UserAccount" ThisKey="userID" OtherKey="UserID" Type="UserAccount" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserAccount" Member="UserAccounts">
    <Type Name="UserAccount">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="passwordHash" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="role" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="UserAccount_Student" Member="Students" ThisKey="UserID" OtherKey="userID" Type="Student" />
      <Association Name="UserAccount_Teacher" Member="Teachers" ThisKey="UserID" OtherKey="userID" Type="Teacher" />
    </Type>
  </Table>
  <Table Name="dbo.Program" Member="Programs">
    <Type Name="Program">
      <Column Name="ProgramID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="programName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="[level]" Member="level" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="duration" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="fee" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="outputStandard" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Program_Class" Member="Classes" ThisKey="ProgramID" OtherKey="programID" Type="Class" />
    </Type>
  </Table>
</Database>